In [0]:
import numpy as np

In [2]:
np.array([10,20,24,5,15,50])

array([10, 20, 24,  5, 15, 50])

In [0]:
a = np.array([10,20, 50, 15, 4, 6, 7 ,100])

In [5]:
a[4]

4

In [6]:
a[3:]

array([ 15,   4,   6,   7, 100])

In [7]:
a[3:6]

array([15,  4,  6])

In [8]:
a[1::2]

array([ 20,  15,   6, 100])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [0]:
b = np.array([['x','y','z'],['a','c','e']])

In [16]:
print(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


In [17]:
type(b)

numpy.ndarray

In [18]:
b.ndim

2

In [0]:
c = [12, 4, 10 , 50 , 2]

In [20]:
np.sort(c)

array([ 2,  4, 10, 12, 50])

In [22]:
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan',10), ('Maria',70), ('Javier', 42), ('Samuel',15)]
usuarios = np.array(datos, dtype=cabeceras)
np.sort(usuarios, order='edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [23]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
np.arange(5,30,5)

array([ 5, 10, 15, 20, 25])

In [26]:
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [27]:
np.diag([0,3,9,10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])